-- Original canonical28 ACLs from an independent installation of the exact
-- source packet. This is recovery-only, never a normal migration or grant
-- to repair an unknown database. The guarded operator verifies complete
-- source, schema, role, backup/restore and retained-data custody first.
SET LOCAL ROLE "creator_trust_owner";
GRANT UPDATE ("available_at") ON TABLE "creator_trust"."effect" TO "creator_trust_runtime";
GRANT UPDATE ("error_code") ON TABLE "creator_trust"."effect" TO "creator_trust_runtime";
GRANT UPDATE ("lease_token") ON TABLE "creator_trust"."effect" TO "creator_trust_runtime";
GRANT UPDATE ("lease_until") ON TABLE "creator_trust"."effect" TO "creator_trust_runtime";
GRANT UPDATE ("state") ON TABLE "creator_trust"."effect" TO "creator_trust_runtime";
GRANT UPDATE ("completed_at") ON TABLE "creator_trust"."privacy_job" TO "creator_trust_runtime";
GRANT UPDATE ("completed_at") ON TABLE "creator_trust"."privacy_job" TO "creator_trust_worker";
GRANT UPDATE ("state") ON TABLE "creator_trust"."privacy_job" TO "creator_trust_runtime";
GRANT UPDATE ("state") ON TABLE "creator_trust"."privacy_job" TO "creator_trust_worker";
GRANT UPDATE ("updated_at") ON TABLE "creator_trust"."privacy_job" TO "creator_trust_runtime";
GRANT UPDATE ("updated_at") ON TABLE "creator_trust"."privacy_job" TO "creator_trust_worker";
SET LOCAL ROLE "creator_owner";
GRANT CREATE, USAGE ON SCHEMA "creator" TO "creator_owner";
GRANT USAGE ON SCHEMA "creator" TO "creator_runtime";
SET LOCAL ROLE "creator_trust_owner";
GRANT CREATE, USAGE ON SCHEMA "creator_trust" TO "creator_trust_owner";
GRANT USAGE ON SCHEMA "creator_trust" TO "creator_trust_runtime";
GRANT USAGE ON SCHEMA "creator_trust" TO "creator_trust_worker";
SET LOCAL ROLE "growth_owner";
GRANT CREATE, USAGE ON SCHEMA "growth" TO "growth_owner";
GRANT USAGE ON SCHEMA "growth" TO "growth_runtime";
GRANT USAGE ON SCHEMA "growth" TO "growth_worker";
SET LOCAL ROLE "creator_trust_owner";
GRANT SELECT, UPDATE, USAGE ON SEQUENCE "creator_trust"."safety_case_number_seq" TO "creator_trust_owner";
GRANT SELECT, USAGE ON SEQUENCE "creator_trust"."safety_case_number_seq" TO "creator_trust_runtime";
GRANT SELECT, USAGE ON SEQUENCE "creator_trust"."safety_case_number_seq" TO "creator_trust_worker";
SET LOCAL ROLE "creator_owner";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."access_grant" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."access_grant" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."ai_chunk" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."ai_chunk" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."ai_command" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."ai_command" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."ai_cost_hold" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."ai_cost_hold" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."ai_evaluation" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."ai_evaluation" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."ai_event" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."ai_event" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."ai_ingestion" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."ai_ingestion" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."ai_license" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."ai_license" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."ai_regression" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."ai_regression" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."ai_shadow_evaluation" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."ai_shadow_evaluation" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."ai_shadow_sample" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."ai_shadow_sample" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."ai_source" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."ai_source" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."ai_sponsor" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."ai_sponsor" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."ai_style_embedding" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."ai_style_embedding" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."ai_tombstone" TO "creator_owner";
GRANT INSERT, SELECT ON TABLE "creator"."ai_tombstone" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."ai_usage" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."ai_usage" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."ai_version" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."ai_version" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."ai_workspace" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."ai_workspace" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."auth_continuation" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."auth_continuation" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."call_admission" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."call_admission" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."call_consent" TO "creator_owner";
GRANT INSERT, SELECT ON TABLE "creator"."call_consent" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."call_effect" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."call_effect" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."call_event" TO "creator_owner";
GRANT INSERT, SELECT ON TABLE "creator"."call_event" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."call_offer" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."call_offer" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."call_outcome" TO "creator_owner";
GRANT INSERT, SELECT ON TABLE "creator"."call_outcome" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."call_session" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."call_session" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."call_slot" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."call_slot" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_allowance_reservation" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_allowance_reservation" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_authorization_lineage" TO "creator_owner";
GRANT INSERT, SELECT ON TABLE "creator"."commerce_authorization_lineage" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_billing_account" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_billing_account" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_billing_effect" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_billing_effect" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_capacity" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_capacity" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_commitment" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_commitment" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_credit_transfer" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_credit_transfer" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_effect" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_effect" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_event" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_event" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_ledger" TO "creator_owner";
GRANT INSERT, SELECT ON TABLE "creator"."commerce_ledger" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_membership" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_membership" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_membership_receipt" TO "creator_owner";
GRANT INSERT, SELECT ON TABLE "creator"."commerce_membership_receipt" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_membership_usage" TO "creator_owner";
GRANT INSERT, SELECT ON TABLE "creator"."commerce_membership_usage" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_mode" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_mode" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_packet" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_packet" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_pass" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_pass" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_pass_purchase_history" TO "creator_owner";
GRANT INSERT, SELECT ON TABLE "creator"."commerce_pass_purchase_history" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_pass_slot" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_pass_slot" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_payout_account" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_payout_account" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_payout_effect" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_payout_effect" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_provider_inbox" TO "creator_owner";
GRANT INSERT ON TABLE "creator"."commerce_provider_inbox" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_qualified_read" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_qualified_read" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_share_grant" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_share_grant" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_spend_limit" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_spend_limit" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_spending_notice" TO "creator_owner";
GRANT INSERT, SELECT ON TABLE "creator"."commerce_spending_notice" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_subscription_history" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_subscription_history" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_tier" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_tier" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."commerce_trial" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."commerce_trial" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."creator_profile" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."creator_profile" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."creator_proof" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."creator_proof" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."event" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."event" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."fan_profile" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."fan_profile" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."generation" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."generation" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."idempotency_key" TO "creator_owner";
GRANT INSERT, SELECT ON TABLE "creator"."idempotency_key" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."identity_event" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."identity_event" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."identity_session" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."identity_session" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."media_asset" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."media_asset" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."memory" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."memory" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."memory_exclusion" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."memory_exclusion" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."message" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."message" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."passkey_credential" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."passkey_credential" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."passkey_registration" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."passkey_registration" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."schema_migration" TO "creator_owner";
GRANT SELECT ON TABLE "creator"."schema_migration" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."signed_act" TO "creator_owner";
GRANT INSERT, SELECT ON TABLE "creator"."signed_act" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."signed_act_consumption" TO "creator_owner";
GRANT INSERT, SELECT ON TABLE "creator"."signed_act_consumption" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."signed_challenge" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."signed_challenge" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."signed_publication" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."signed_publication" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."signed_verification" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."signed_verification" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."team_invitation" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."team_invitation" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."team_membership" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."team_membership" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."thread" TO "creator_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "creator"."thread" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."thread_audit" TO "creator_owner";
GRANT INSERT, SELECT ON TABLE "creator"."thread_audit" TO "creator_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator"."webhook_inbox" TO "creator_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator"."webhook_inbox" TO "creator_runtime";
SET LOCAL ROLE "creator_trust_owner";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."access_audit" TO "creator_trust_owner";
GRANT INSERT, SELECT ON TABLE "creator_trust"."access_audit" TO "creator_trust_runtime";
GRANT SELECT ON TABLE "creator_trust"."access_audit" TO "creator_trust_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."block" TO "creator_trust_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator_trust"."block" TO "creator_trust_runtime";
GRANT SELECT ON TABLE "creator_trust"."block" TO "creator_trust_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."case_access" TO "creator_trust_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator_trust"."case_access" TO "creator_trust_runtime";
GRANT SELECT ON TABLE "creator_trust"."case_access" TO "creator_trust_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."case_event" TO "creator_trust_owner";
GRANT INSERT, SELECT ON TABLE "creator_trust"."case_event" TO "creator_trust_runtime";
GRANT SELECT, UPDATE ON TABLE "creator_trust"."case_event" TO "creator_trust_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."case_evidence" TO "creator_trust_owner";
GRANT INSERT, SELECT ON TABLE "creator_trust"."case_evidence" TO "creator_trust_runtime";
GRANT DELETE, SELECT, UPDATE ON TABLE "creator_trust"."case_evidence" TO "creator_trust_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."command" TO "creator_trust_owner";
GRANT INSERT, SELECT ON TABLE "creator_trust"."command" TO "creator_trust_runtime";
GRANT SELECT, UPDATE ON TABLE "creator_trust"."command" TO "creator_trust_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."crisis_counter" TO "creator_trust_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator_trust"."crisis_counter" TO "creator_trust_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."crisis_referral_event" TO "creator_trust_owner";
GRANT INSERT, SELECT ON TABLE "creator_trust"."crisis_referral_event" TO "creator_trust_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."effect" TO "creator_trust_owner";
GRANT INSERT, SELECT ON TABLE "creator_trust"."effect" TO "creator_trust_runtime";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator_trust"."effect" TO "creator_trust_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."feedback" TO "creator_trust_owner";
GRANT INSERT, SELECT ON TABLE "creator_trust"."feedback" TO "creator_trust_runtime";
GRANT DELETE, SELECT ON TABLE "creator_trust"."feedback" TO "creator_trust_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."notice" TO "creator_trust_owner";
GRANT INSERT, SELECT ON TABLE "creator_trust"."notice" TO "creator_trust_runtime";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator_trust"."notice" TO "creator_trust_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."ops_member" TO "creator_trust_owner";
GRANT SELECT ON TABLE "creator_trust"."ops_member" TO "creator_trust_runtime";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."privacy_job" TO "creator_trust_owner";
GRANT INSERT, SELECT ON TABLE "creator_trust"."privacy_job" TO "creator_trust_runtime";
GRANT INSERT, SELECT ON TABLE "creator_trust"."privacy_job" TO "creator_trust_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."privacy_task" TO "creator_trust_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator_trust"."privacy_task" TO "creator_trust_runtime";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator_trust"."privacy_task" TO "creator_trust_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."restriction" TO "creator_trust_owner";
GRANT INSERT, SELECT ON TABLE "creator_trust"."restriction" TO "creator_trust_runtime";
GRANT SELECT ON TABLE "creator_trust"."restriction" TO "creator_trust_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."retained_record" TO "creator_trust_owner";
GRANT INSERT, SELECT ON TABLE "creator_trust"."retained_record" TO "creator_trust_runtime";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator_trust"."retained_record" TO "creator_trust_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."safety_case" TO "creator_trust_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator_trust"."safety_case" TO "creator_trust_runtime";
GRANT INSERT, SELECT, UPDATE ON TABLE "creator_trust"."safety_case" TO "creator_trust_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."service_incident" TO "creator_trust_owner";
GRANT SELECT ON TABLE "creator_trust"."service_incident" TO "creator_trust_runtime";
GRANT SELECT ON TABLE "creator_trust"."service_incident" TO "creator_trust_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "creator_trust"."tombstone" TO "creator_trust_owner";
GRANT INSERT, SELECT ON TABLE "creator_trust"."tombstone" TO "creator_trust_runtime";
GRANT SELECT ON TABLE "creator_trust"."tombstone" TO "creator_trust_worker";
SET LOCAL ROLE "growth_owner";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."activation_job" TO "growth_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."activation_job" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."content_public" TO "growth_owner";
GRANT SELECT ON TABLE "growth"."content_public" TO "growth_runtime";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."content_public" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."creator_public" TO "growth_owner";
GRANT SELECT ON TABLE "growth"."creator_public" TO "growth_runtime";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."creator_public" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."delivery" TO "growth_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."delivery" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."device" TO "growth_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."device" TO "growth_runtime";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."device" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."email" TO "growth_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."email" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."event_inbox" TO "growth_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."event_inbox" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."experiment" TO "growth_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."experiment" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."feedback" TO "growth_owner";
GRANT INSERT, SELECT ON TABLE "growth"."feedback" TO "growth_runtime";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."feedback" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."follow" TO "growth_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."follow" TO "growth_runtime";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."follow" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."impact" TO "growth_owner";
GRANT SELECT ON TABLE "growth"."impact" TO "growth_runtime";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."impact" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."insight_signal" TO "growth_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."insight_signal" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."insight_snapshot" TO "growth_owner";
GRANT SELECT ON TABLE "growth"."insight_snapshot" TO "growth_runtime";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."insight_snapshot" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."insight_window" TO "growth_owner";
GRANT SELECT ON TABLE "growth"."insight_window" TO "growth_runtime";
GRANT DELETE, INSERT, SELECT ON TABLE "growth"."insight_window" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."instagram_reply" TO "growth_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."instagram_reply" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."invite" TO "growth_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "growth"."invite" TO "growth_runtime";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."invite" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."metric" TO "growth_owner";
GRANT INSERT, SELECT ON TABLE "growth"."metric" TO "growth_runtime";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."metric" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."notification" TO "growth_owner";
GRANT SELECT, UPDATE ON TABLE "growth"."notification" TO "growth_runtime";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."notification" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."preference" TO "growth_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."preference" TO "growth_runtime";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."preference" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."provider_receipt" TO "growth_owner";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."provider_receipt" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."recommendation" TO "growth_owner";
GRANT INSERT, SELECT, UPDATE ON TABLE "growth"."recommendation" TO "growth_runtime";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."recommendation" TO "growth_worker";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "growth"."share" TO "growth_owner";
GRANT INSERT, SELECT ON TABLE "growth"."share" TO "growth_runtime";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "growth"."share" TO "growth_worker";
RESET ROLE;
