// Generated. Run pnpm generate.
export const themes = {
  "light": {
    "ground": "#F3F2EE",
    "surface": "#FFFFFF",
    "surface-sunken": "#E6E4DE",
    "line": "#DAD8D2",
    "control-line": "#7F7D78",
    "ink": "#1B1A18",
    "ink-muted": "#5C5B57",
    "ai-surface": "#FFFFFF",
    "ai-line": "#C8D2DC",
    "ai-ink": "#3A6795",
    "on-ai": "#FFFFFF",
    "maya-surface": "#1C1B19",
    "maya-line": "#1C1B19",
    "on-maya": "#F4F1EA",
    "on-maya-muted": "#ABA8A1",
    "maya-accent": "#EE8D5F",
    "on-maya-accent": "#1C1B19",
    "maya-ink": "#7E2E12",
    "team-surface": "#ECEAE5",
    "team-ink": "#5C5B57",
    "alert": "#B42318",
    "focus": "#1B1A18",
    "focus-on-maya": "#EE8D5F",
    "seal-fill": "#EE8D5F",
    "seal-ink": "#1C1B19",
    "selected-surface": "#FFFFFF",
    "overlay-scrim": "#1C1B1973",
    "plate-rule": "#FFFFFF",
    "shadow-plate": "0 20px 34px -24px rgba(28,27,25,0.8)",
    "shadow-sheet": "0 -12px 40px rgba(28,27,25,0.22)",
    "glow-maya": "0 18px 38px -20px rgba(238,141,95,0.62)"
  },
  "night": {
    "ground": "#14120F",
    "surface": "#211E1A",
    "surface-sunken": "#2A2621",
    "line": "#3A342D",
    "control-line": "#80796E",
    "ink": "#ECE6DA",
    "ink-muted": "#A39C8F",
    "ai-surface": "#1B1F23",
    "ai-line": "#3A4652",
    "ai-ink": "#A3B8CC",
    "on-ai": "#14120F",
    "maya-surface": "#EDE3D3",
    "maya-line": "#5A3F2C",
    "on-maya": "#231C16",
    "on-maya-muted": "#5E5246",
    "maya-accent": "#8E3514",
    "on-maya-accent": "#FBF5EC",
    "maya-ink": "#E89A6E",
    "team-surface": "#24221F",
    "team-ink": "#A39C8F",
    "alert": "#FF8A7A",
    "focus": "#ECE6DA",
    "focus-on-maya": "#8E3514",
    "seal-fill": "#E89A6E",
    "seal-ink": "#14120F",
    "selected-surface": "#211E1A",
    "overlay-scrim": "#00000099",
    "plate-rule": "#FFFFFF",
    "shadow-plate": "0 20px 34px -24px rgba(0,0,0,0.9)",
    "shadow-sheet": "0 -12px 40px rgba(0,0,0,0.6)",
    "glow-maya": "0 18px 40px -22px rgba(232,154,110,0.62)"
  }
} as const;
export const dimensions = {
  "space-1": 4,
  "space-2": 8,
  "space-3": 12,
  "space-4": 16,
  "space-5": 20,
  "space-6": 24,
  "space-8": 32,
  "space-12": 48,
  "radius-tail": 4,
  "radius-sm": 8,
  "radius-md": 12,
  "radius-lg": 14,
  "radius-xl": 20,
  "radius-pill": 999,
  "z-strip": 10,
  "z-composer": 20,
  "z-sheet": 40,
  "phone-width": 390,
  "phone-height": 844,
  "desktop-width": 1280,
  "sidebar-width": 248,
  "welcome-top": 64,
  "welcome-bottom": 40,
  "welcome-gap": 28,
  "welcome-wordmark": 22,
  "welcome-title": 44,
  "welcome-title-line": 46,
  "welcome-mark-width": 120,
  "welcome-mark-height": 56,
  "touch-target": 44,
  "button-lg": 56,
  "author-label-size": 12,
  "author-label-line": 17,
  "author-gap": 6,
  "message-max-width": 334,
  "fan-message-max-width": 286,
  "message-padding": 14,
  "note-fold": 28,
  "hairline": 1,
  "glyph-size": 22,
  "avatar-size": 38,
  "segment-height": 40,
  "segment-radius": 10,
  "sidebar-min-height": 600,
  "dialog-width": 340,
  "dialog-padding": 22,
  "toast-width": 358,
  "sheet-grabber-width": 38,
  "sheet-grabber-height": 5,
  "sheet-grabber-radius": 3,
  "skeleton-width": 300,
  "skeleton-label-width": 88,
  "skeleton-bubble-height": 72,
  "skeleton-radius": 6,
  "avatar-radius": 11,
  "strip-min-height": 42,
  "strip-box-radius": 7,
  "glyph-small": 12,
  "glyph-caption": 13,
  "glyph-inline": 14,
  "seal-step": 30,
  "seal-reaction": 22,
  "seal-presence": 18,
  "chip-radius": 10,
  "citation-stamp-width": 34,
  "citation-stamp-height": 26,
  "citation-stamp-size": 10,
  "access-term-width": 96,
  "checkbox-size": 20,
  "limit-radio-size": 18,
  "include-row-height": 52,
  "request-dot-size": 9,
  "request-dot-inset": 3,
  "request-dot-stroke": 1.5,
  "receipt-max-width": 460,
  "receipt-padding-x": 28,
  "receipt-padding-y": 26,
  "receipt-radius": 6,
  "composer-bottom": 28,
  "composer-gap": 10,
  "composer-input-height": 48,
  "wave-bar-width": 3,
  "wave-gap": 2,
  "wave-radius": 2,
  "share-size": 340,
  "share-padding": 26,
  "share-gap": 18,
  "countdown-height": 26,
  "call-person-height": 40,
  "call-recording-height": 32,
  "notification-radius": 11,
  "signing-label-width": 88,
  "transcript-label-width": 84,
  "version-id-width": 36,
  "wave-bar-8": 8,
  "wave-bar-10": 10,
  "wave-bar-12": 12,
  "wave-bar-14": 14,
  "wave-bar-16": 16,
  "wave-bar-18": 18,
  "wave-bar-20": 20,
  "wave-bar-22": 22,
  "wave-bar-24": 24,
  "wave-bar-26": 26,
  "glow-opacity": 0.62,
  "seal-font-ratio": 0.62,
  "wave-opacity": 0.55,
  "presence-line-opacity": 0.5,
  "strip-glow-opacity": 0.24,
  "capacity-rule-opacity": 0.09,
  "share-rule-opacity": 0.1,
  "strip-glow-x": 0.18,
  "strip-glow-stop": 0.55,
  "strip-glow-scale-x": 1.2,
  "strip-glow-scale-y": 1.6,
  "note-fold-opacity": 0.14,
  "note-media-opacity": 0.18,
  "note-media-height": 150
} as const;
export const textStyles = {
  "display-xl": {
    "family": "serif",
    "size": 64,
    "lineHeight": 60,
    "weight": 400,
    "letterSpacing": -0.03
  },
  "display-lg": {
    "family": "serif",
    "size": 34,
    "lineHeight": 36,
    "weight": 400,
    "letterSpacing": -0.02
  },
  "display-md": {
    "family": "serif",
    "size": 26,
    "lineHeight": 30,
    "weight": 400,
    "letterSpacing": -0.015
  },
  "voice-lg": {
    "family": "serif",
    "size": 18,
    "lineHeight": 28,
    "weight": 400,
    "letterSpacing": 0
  },
  "voice-md": {
    "family": "serif",
    "size": 16,
    "lineHeight": 24,
    "weight": 400,
    "letterSpacing": 0
  },
  "title": {
    "family": "sans",
    "size": 17,
    "lineHeight": 22,
    "weight": 600,
    "letterSpacing": -0.015
  },
  "body": {
    "family": "sans",
    "size": 15,
    "lineHeight": 22,
    "weight": 400,
    "letterSpacing": 0
  },
  "body-strong": {
    "family": "sans",
    "size": 15,
    "lineHeight": 22,
    "weight": 600,
    "letterSpacing": 0
  },
  "label": {
    "family": "sans",
    "size": 13,
    "lineHeight": 18,
    "weight": 600,
    "letterSpacing": 0
  },
  "caption": {
    "family": "sans",
    "size": 12,
    "lineHeight": 17,
    "weight": 400,
    "letterSpacing": 0
  },
  "data-lg": {
    "family": "mono",
    "size": 24,
    "lineHeight": 28,
    "weight": 400,
    "letterSpacing": 0
  },
  "data-md": {
    "family": "mono",
    "size": 15,
    "lineHeight": 20,
    "weight": 400,
    "letterSpacing": 0
  },
  "data-sm": {
    "family": "mono",
    "size": 11,
    "lineHeight": 14,
    "weight": 400,
    "letterSpacing": 0.05
  },
  "control-body": {
    "family": "sans",
    "size": 14,
    "lineHeight": 20,
    "weight": 400,
    "letterSpacing": 0
  },
  "tab-label": {
    "family": "sans",
    "size": 11,
    "lineHeight": 16,
    "weight": 600,
    "letterSpacing": 0
  },
  "summary": {
    "family": "sans",
    "size": 17,
    "lineHeight": 24,
    "weight": 400,
    "letterSpacing": 0
  },
  "receipt-title": {
    "family": "serif",
    "size": 28,
    "lineHeight": 32,
    "weight": 400,
    "letterSpacing": -0.01
  },
  "transcript-human": {
    "family": "serif",
    "size": 15,
    "lineHeight": 22,
    "weight": 400,
    "letterSpacing": 0
  },
  "transcript-ai": {
    "family": "sans",
    "size": 13,
    "lineHeight": 19,
    "weight": 400,
    "letterSpacing": 0
  },
  "mono-caption": {
    "family": "mono",
    "size": 12,
    "lineHeight": 17,
    "weight": 400,
    "letterSpacing": 0
  },
  "signing-title": {
    "family": "serif",
    "size": 28,
    "lineHeight": 32,
    "weight": 400,
    "letterSpacing": 0
  },
  "share-quote": {
    "family": "serif",
    "size": 22,
    "lineHeight": 31,
    "weight": 400,
    "letterSpacing": 0
  },
  "data-label": {
    "family": "mono",
    "size": 13,
    "lineHeight": 20,
    "weight": 400,
    "letterSpacing": 0
  },
  "signing-label": {
    "family": "mono",
    "size": 11,
    "lineHeight": 20,
    "weight": 400,
    "letterSpacing": 0.05
  },
  "email-brand": {
    "family": "serif",
    "size": 22,
    "lineHeight": 26,
    "weight": 400,
    "letterSpacing": 0
  },
  "sidebar-brand": {
    "family": "serif",
    "size": 14,
    "lineHeight": 18,
    "weight": 400,
    "letterSpacing": 0
  },
  "citation-stamp": {
    "family": "mono",
    "size": 10,
    "lineHeight": 10,
    "weight": 500,
    "letterSpacing": 0
  },
  "access-term": {
    "family": "mono",
    "size": 11,
    "lineHeight": 20,
    "weight": 400,
    "letterSpacing": 0.05
  },
  "mode-title": {
    "family": "sans",
    "size": 15,
    "lineHeight": 20,
    "weight": 600,
    "letterSpacing": 0
  },
  "control-compact": {
    "family": "sans",
    "size": 13,
    "lineHeight": 20,
    "weight": 600,
    "letterSpacing": 0
  },
  "badge": {
    "family": "mono",
    "size": 11,
    "lineHeight": 14,
    "weight": 500,
    "letterSpacing": 0.04
  },
  "button-lg": {
    "family": "sans",
    "size": 16,
    "lineHeight": 22,
    "weight": 600,
    "letterSpacing": 0
  },
  "context-body": {
    "family": "sans",
    "size": 14,
    "lineHeight": 19,
    "weight": 400,
    "letterSpacing": 0
  }
} as const;
export type Theme = keyof typeof themes;
export type ColorToken = keyof typeof themes.light;
